// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"webook/sms/grpc"
	"webook/sms/ioc"
)

// Injectors from wire.go:

func InitApp() *App {
	smsService := ioc.InitSmsService()
	smsServiceServer := grpc.NewSmsServiceServer(smsService)
	loggerV1 := ioc.InitLogger()
	server := ioc.NewGrpcxServer(smsServiceServer, loggerV1)
	app := &App{
		server: server,
	}
	return app
}
