// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"webook/article/events/article"
	"webook/article/grpc"
	"webook/article/ioc"
	"webook/article/repository"
	"webook/article/repository/cache"
	"webook/article/repository/dao"
	"webook/article/service"
)

// Injectors from wire.go:

func InitApp() *App {
	loggerV1 := ioc.InitLogger()
	db := ioc.InitDB(loggerV1)
	articleDao := dao.NewArticleGORMDAO(db)
	cmdable := ioc.InitRedis()
	articleCache := cache.NewArticleRedisCache(cmdable)
	articleRepository := repository.NewCachedArticleRepository(articleDao, articleCache, loggerV1)
	client := ioc.InitSaramaClient()
	syncProducer := ioc.InitSyncProducer(client)
	producer := article.NewSaramaSyncProducer(syncProducer)
	clientv3Client := ioc.InitEtcd()
	userServiceClient := ioc.InitUserClient(clientv3Client)
	articleService := service.NewArticleService(articleRepository, producer, userServiceClient)
	articleServiceServer := grpc.NewArticleServiceServer(articleService)
	server := ioc.NewGrpcxServer(articleServiceServer, loggerV1)
	mysqlBinlogConsumer := article.NewMysqlBinlogConsumer(client, loggerV1)
	v := ioc.InitConsumers(mysqlBinlogConsumer)
	app := &App{
		server:    server,
		consumers: v,
	}
	return app
}
