// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/interactive/events"
	"webook/interactive/grpc"
	"webook/interactive/ioc"
	"webook/interactive/repository"
	"webook/interactive/repository/cache"
	"webook/interactive/repository/dao"
	"webook/interactive/service"
)

import (
	_ "github.com/spf13/viper/remote"
)

// Injectors from wire.go:

func InitApp() *App {
	srcDB := ioc.InitSrcDB()
	dstDB := ioc.InitDstDB()
	loggerV1 := ioc.InitLogger()
	doubleWritePool := ioc.InitDoubleWritePool(srcDB, dstDB, loggerV1)
	db := ioc.InitBizDB(doubleWritePool)
	interactiveDAO := dao.NewGORMInteractiveDAO(db)
	cmdable := ioc.InitRedis()
	interactiveCache := cache.NewInteractiveRedisCache(cmdable)
	interactiveRepository := repository.NewCachedInteractiveRepository(interactiveDAO, interactiveCache, loggerV1)
	client := ioc.InitSaramaClient()
	interactiveReadEventConsumer := events.NewInteractiveReadEventConsumer(interactiveRepository, client, loggerV1)
	consumer := ioc.InitFixerConsumer(client, loggerV1, srcDB, dstDB)
	v := ioc.InitConsumers(interactiveReadEventConsumer, consumer)
	syncProducer := ioc.InitSaramaSyncProducer(client)
	producer := events.NewInteractiveProducer(syncProducer)
	interactiveService := service.NewInteractiveService(interactiveRepository, producer, loggerV1)
	interactiveServiceServer := grpc.NewInteractiveServiceServer(interactiveService)
	server := ioc.NewGrpcxServer(interactiveServiceServer, loggerV1)
	eventsProducer := ioc.InitInteractiveProducer(syncProducer)
	ginxServer := ioc.InitGinxServer(loggerV1, srcDB, dstDB, doubleWritePool, eventsProducer)
	app := &App{
		consumers:   v,
		server:      server,
		adminServer: ginxServer,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitSrcDB, ioc.InitDstDB, ioc.InitBizDB, ioc.InitDoubleWritePool, ioc.InitLogger, ioc.InitRedis, ioc.InitSaramaClient, ioc.InitSaramaSyncProducer)

var interactiveSvcSet = wire.NewSet(dao.NewGORMInteractiveDAO, cache.NewInteractiveRedisCache, repository.NewCachedInteractiveRepository, service.NewInteractiveService)
