// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/comment/grpc"
	"webook/comment/ioc"
	"webook/comment/repository"
	"webook/comment/repository/dao"
	"webook/comment/service"
)

// Injectors from wire.go:

func InitApp() *App {
	db := ioc.InitDB()
	commentDAO := dao.NewCommentGORMDAO(db)
	loggerV1 := ioc.InitLogger()
	commentRepository := repository.NewCommentRepository(commentDAO, loggerV1)
	commentService := service.NewCommentService(commentRepository)
	commentServiceServer := grpc.NewCommentServiceServer(commentService)
	server := ioc.NewGrpcServer(commentServiceServer, loggerV1)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitLogger)
