// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/search/events"
	"webook/search/grpc"
	"webook/search/ioc"
	"webook/search/repository"
	"webook/search/repository/dao"
	"webook/search/service"
)

// Injectors from wire.go:

func InitApp() *App {
	client := ioc.InitES()
	userSearchDAO := dao.NewUserESDAO(client)
	userSearchRepository := repository.NewUserSearchRepository(userSearchDAO)
	articleSearchDAO := dao.NewArticleESDAO(client)
	tagDAO := dao.NewTagESDAO(client)
	likeDAO := dao.NewLikeESDAO(client)
	collectDAO := dao.NewCollectESDAO(client)
	articleSearchRepository := repository.NewArticleSearchRepository(articleSearchDAO, tagDAO, likeDAO, collectDAO)
	anyDAO := dao.NewAnyESDAO(client)
	anyRepository := repository.NewAnyRepository(anyDAO)
	syncService := service.NewSyncService(userSearchRepository, articleSearchRepository, anyRepository)
	saramaClient := ioc.InitSamara()
	loggerV1 := ioc.InitLogger()
	articleConsumer := events.NewArticleConsumer(syncService, saramaClient, loggerV1)
	interactiveConsumer := events.NewInteractiveConsumer(saramaClient, syncService, loggerV1)
	syncDataEventConsumer := events.NewSyncDataEventConsumer(syncService, saramaClient, loggerV1)
	userConsumer := events.NewUserConsumer(syncService, saramaClient, loggerV1)
	v := ioc.NewConsumers(articleConsumer, interactiveConsumer, syncDataEventConsumer, userConsumer)
	searchService := service.NewSearchService(userSearchRepository, articleSearchRepository)
	searchServiceServer := grpc.NewSearchServiceServer(searchService)
	syncServiceServer := grpc.NewSyncServiceServer(syncService)
	server := ioc.InitGrpc(searchServiceServer, syncServiceServer, loggerV1)
	app := &App{
		consumers: v,
		server:    server,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitES, ioc.InitSamara, ioc.InitLogger)
