// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/feed/events"
	"webook/feed/grpc"
	"webook/feed/ioc"
	"webook/feed/repository"
	"webook/feed/repository/dao"
	"webook/feed/service"
)

// Injectors from wire.go:

func InitApp() *App {
	db := ioc.InitDB()
	feedPullEventDAO := dao.NewFeedPullEventGORMDAO(db)
	feedPushEventDAO := dao.NewFeedPushEventGORMDAO(db)
	feedRepository := repository.NewFeedEventRepo(feedPullEventDAO, feedPushEventDAO)
	client := ioc.InitEtcd()
	followServiceClient := ioc.InitFollowClient(client)
	v := ioc.RegisterHandler(feedRepository, followServiceClient)
	feedService := service.NewFeedService(feedRepository, v)
	feedServiceServer := grpc.NewFeedServiceServer(feedService)
	loggerV1 := ioc.InitLogger()
	server := ioc.InitGrpc(feedServiceServer, loggerV1)
	saramaClient := ioc.InitKafka()
	feedEventConsumer := events.NewFeedEventConsumer(saramaClient, loggerV1, feedService)
	v2 := ioc.InitConsumer(feedEventConsumer)
	app := &App{
		server:   server,
		consumer: v2,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitLogger, ioc.InitKafka, ioc.InitEtcd)
