// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"webook/bff/ioc"
	"webook/bff/web"
	"webook/bff/web/jwt"
)

// Injectors from wire.go:

func InitApp() *App {
	cmdable := ioc.InitRedis()
	handler := jwt.NewRedisJWTHandler(cmdable)
	loggerV1 := ioc.InitLogger()
	v := ioc.InitGinMiddlewares(cmdable, handler, loggerV1)
	client := ioc.InitEtcd()
	userServiceClient := ioc.InitUserClient(client)
	codeServiceClient := ioc.InitCodeClient(client)
	userHandler := web.NewUserHandler(userServiceClient, handler, codeServiceClient)
	oauth2ServiceClient := ioc.InitOauth2Client(client)
	oAuth2WechatHandler := web.NewOAuth2WechatHandler(oauth2ServiceClient, handler, userServiceClient)
	articleServiceClient := ioc.InitArticleClient(client)
	interactiveServiceClient := ioc.InitIntrClient(client)
	rewardServiceClient := ioc.InitRewardClient(client)
	commentServiceClient := ioc.InitCommentClient(client)
	articleHandler := web.NewArticleHandler(articleServiceClient, loggerV1, interactiveServiceClient, rewardServiceClient, commentServiceClient)
	server := ioc.InitWebServer(v, userHandler, oAuth2WechatHandler, articleHandler)
	app := &App{
		webServer: server,
	}
	return app
}
