// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"webook/oauth2/grpc"
	"webook/oauth2/ioc"
)

// Injectors from wire.go:

func InitApp() *App {
	loggerV1 := ioc.InitLogger()
	oauth2Service := ioc.InitPrometheus(loggerV1)
	oauth2ServiceServer := grpc.NewOauth2ServiceServer(oauth2Service)
	server := ioc.NewGrpcxServer(oauth2ServiceServer, loggerV1)
	app := &App{
		server: server,
	}
	return app
}
