// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"webook/code/grpc"
	"webook/code/ioc"
	"webook/code/repository"
	"webook/code/repository/cache"
	"webook/code/service"
)

// Injectors from wire.go:

func InitApp() *App {
	cmdable := ioc.InitRedis()
	codeCache := cache.NewRedisCodeCache(cmdable)
	codeRepository := repository.NewCodeRepository(codeCache)
	client := ioc.InitEtcd()
	smsServiceClient := ioc.InitSmslient(client)
	codeService := service.NewCodeService(codeRepository, smsServiceClient)
	codeServiceServer := grpc.NewCodeServiceServer(codeService)
	loggerV1 := ioc.InitLogger()
	server := ioc.NewGrpcxServer(codeServiceServer, loggerV1)
	app := &App{
		server: server,
	}
	return app
}
