test:
  key: "comment"

redis:
  addr: "43.154.97.245:6379"

db:
  dsn: "root:root@tcp(43.154.97.245:13316)/webook_comment"

kafka:
  addr:
    - "43.154.97.245:9094"

etcd:
  etcdAddr: "43.154.97.245:12379"
  username: "root"
  password: "1234"

grpc:
  server:
    etcdAddr: "43.154.97.245:12379"
    port: 8094
    name: "comment"