// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"webook/mysqljob/grpc"
	"webook/mysqljob/ioc"
	"webook/mysqljob/repository"
	"webook/mysqljob/repository/dao"
	"webook/mysqljob/service"
)

// Injectors from wire.go:

func InitApp() *App {
	db := ioc.InitDB()
	jobDAO := dao.NewGORMJobDAO(db)
	cronJobRepository := repository.NewPreemptJobRepository(jobDAO)
	loggerV1 := ioc.InitLogger()
	cronJobService := service.NewCronJobService(cronJobRepository, loggerV1)
	mysqlCronJobServiceServer := grpc.NewMysqlCronJobServiceServer(cronJobService)
	server := ioc.NewGrpcxServer(mysqlCronJobServiceServer, loggerV1)
	scheduler := ioc.InitScheduler(cronJobService, loggerV1)
	app := &App{
		server: server,
		job:    scheduler,
	}
	return app
}
