// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"webook/ranking/grpc"
	"webook/ranking/ioc"
	"webook/ranking/repository"
	"webook/ranking/repository/cache"
	"webook/ranking/service"
)

// Injectors from wire.go:

func InitApp() *App {
	client := ioc.InitEtcd()
	interactiveServiceClient := ioc.InitIntrClient(client)
	articleServiceClient := ioc.InitArtClient(client)
	cmdable := ioc.InitRedis()
	rankingCache := cache.NewRankingRedisCache(cmdable)
	rankingRepository := repository.NewCachedRankingRepository(rankingCache)
	rankingService := service.NewBatchRankingService(interactiveServiceClient, articleServiceClient, rankingRepository)
	rankingServiceServer := grpc.NewRankingServiceServer(rankingService)
	loggerV1 := ioc.InitLogger()
	server := ioc.NewGrpcxServer(rankingServiceServer, loggerV1)
	rlockClient := ioc.InitRlockClient(cmdable)
	rankingJob := ioc.InitRankingJob(rankingService, rlockClient, loggerV1)
	cron := ioc.InitJobs(loggerV1, rankingJob)
	app := &App{
		server: server,
		cron:   cron,
	}
	return app
}
