// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/account/grpc"
	"webook/account/ioc"
	"webook/account/repository"
	"webook/account/repository/cache"
	"webook/account/repository/dao"
	"webook/account/service"
)

// Injectors from wire.go:

func InitApp() *App {
	db := ioc.InitDB()
	accountDAO := dao.NewAccountGORMDAO(db)
	cmdable := ioc.InitRedis()
	accountCache := cache.NewAccountRedisCache(cmdable)
	accountRepository := repository.NewAccountRepository(accountDAO, accountCache)
	loggerV1 := ioc.InitLogger()
	accountService := service.NewAccountService(accountRepository, loggerV1)
	accountServiceServer := grpc.NewAccountServiceServer(accountService)
	server := ioc.NewGrpcxServer(accountServiceServer, loggerV1)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitLogger, ioc.InitRedis)
