// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/follow/events"
	"webook/follow/grpc"
	"webook/follow/ioc"
	"webook/follow/repository"
	"webook/follow/repository/cache"
	"webook/follow/repository/dao"
	"webook/follow/service"
)

// Injectors from wire.go:

func InitApp() *App {
	db := ioc.InitDB()
	followDAO := dao.NewFollowGROMDAO(db)
	cmdable := ioc.InitRedis()
	followCache := cache.NewFollowRedisCache(cmdable)
	loggerV1 := ioc.InitLogger()
	followRepository := repository.NewFollowRelationRepository(followDAO, followCache, loggerV1)
	followService := service.NewFollowRelationService(followRepository)
	followRelationServiceServer := grpc.NewFollowRelationServiceServer(followService)
	server := ioc.NewGrpcServer(followRelationServiceServer, loggerV1)
	client := ioc.InitKafka()
	mysqlBinlogConsumer := events.NewMysqlBinlogConsumer(client, loggerV1, followCache)
	v := ioc.InitConsumer(mysqlBinlogConsumer)
	app := &App{
		server:   server,
		consumer: v,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitLogger, ioc.InitRedis, ioc.InitKafka)
