// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/reward/events"
	"webook/reward/grpc"
	"webook/reward/ioc"
	"webook/reward/repository"
	"webook/reward/repository/cache"
	"webook/reward/repository/dao"
	"webook/reward/service"
)

// Injectors from wire.go:

func InitApp() *App {
	client := ioc.InitEtcd()
	wechatPaymentServiceClient := ioc.InitPaymentClient(client)
	accountServiceClient := ioc.InitAccountClient(client)
	db := ioc.InitDB()
	rewardDAO := dao.NewRewardGORMDAO(db)
	cmdable := ioc.InitRedis()
	rewardCache := cache.NewRewardRedisCache(cmdable)
	rewardRepository := repository.NewRewardRepository(rewardDAO, rewardCache)
	loggerV1 := ioc.InitLogger()
	rewardService := service.NewWechatNativeRewardService(wechatPaymentServiceClient, accountServiceClient, rewardRepository, loggerV1)
	rewardServiceServer := grpc.NewRewardServiceServer(rewardService)
	server := ioc.NewGrpcxServer(rewardServiceServer, loggerV1)
	saramaClient := ioc.InitSaramaClient()
	paymentEventConsumer := events.NewPaymentEventConsumer(saramaClient, loggerV1, rewardService)
	consumer := ioc.InitConsumers(paymentEventConsumer)
	app := &App{
		server:   server,
		consumer: consumer,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitRedis, ioc.InitLogger, ioc.InitSaramaClient, ioc.InitEtcd)
