// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/tag/events"
	"webook/tag/grpc"
	"webook/tag/ioc"
	"webook/tag/repository"
	"webook/tag/repository/cache"
	"webook/tag/repository/dao"
	"webook/tag/service"
)

// Injectors from wire.go:

func InitApp() *App {
	db := ioc.InitDB()
	tagDAO := dao.NewTagGORMDAO(db)
	cmdable := ioc.InitRedis()
	tagCache := cache.NewTagRedisCache(cmdable)
	loggerV1 := ioc.InitLogger()
	tagRepository := repository.NewTagRepository(tagDAO, tagCache, loggerV1)
	client := ioc.InitKafka()
	syncProducer := ioc.InitSaramaSyncProducer(client)
	producer := events.NewSaramaSyncProducer(syncProducer)
	tagService := service.NewTagService(tagRepository, producer, loggerV1)
	tagServiceServer := grpc.NewTagServiceServer(tagService)
	server := ioc.InitGrpc(tagServiceServer, loggerV1)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitLogger, ioc.InitKafka, ioc.InitRedis, ioc.InitSaramaSyncProducer)
