test:
  key: "article"

redis:
  addr: "43.154.97.245:6379"

db:
  dsn: "root:root@tcp(43.154.97.245:13316)/webook_article"

kafka:
  addr:
    - "43.154.97.245:9094"

# grpc客户端调用grpc服务
grpc:
  server:
    etcdAddr: "43.154.97.245:12379"
    port: 8200
    name: "article"
  client:
    user:
      target: "etcd:///service/user"

etcd:
  etcdAddr: "43.154.97.245:12379"
  username: "root"
  password: "1234"